<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rpl</string>
	</array>
	<key>firstLineMatch</key>
	<string>RPL[\w\s]*\{</string>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>\}</string>
	<key>name</key>
	<string>Resource Replacement Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#struct</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.rpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.rpl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((#).*)\r?\n?</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\$(?:[\da-fA-F]{2}|\([\da-fA-F]+\)|["“”„‟'‘’‚‛『』「」«»‹›znrt$]|(.))</string>
			<key>name</key>
			<string>constant.character.escape.rpl</string>
		</dict>
		<key>index</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.rpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.rpl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.rpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.rpl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-struct</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.rpl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(?=\S)(?!\d+|--|[$@\[#,"“”„‟'‘’‚‛『』「」«»‹›`–—―]|\w+\d*\s*[({\[])(?:(false|true|undefined|black|white|red|blue|green|yellow|magenta|pink|cyan|gray|grey|transparent|byte|short|long|double|LRUD|LRDU|RLUD|RLDU|UDLR|UDRL|DULR|DURL|LU|LD|RU|RD|UL|UR|DL|DR|big|little)|([^:,#(){}\[\]\r\n]+))</string>
		</dict>
		<key>math-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.rpl</string>
					<key>match</key>
					<string>\*\*|&lt;&lt;|&gt;&gt;|[+\-*/&amp;|^]|%(?=\s*[+\-(&lt;\d])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.rpl</string>
					<key>match</key>
					<string>(\$\$|0x)[\da-fA-F]+|\d+|0o?[0-7]+|(0b|%)[01]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.brace.round.rpl</string>
					<key>match</key>
					<string>\(|\)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.generic.rpl</string>
					<key>match</key>
					<string>(&lt;)|(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.generic.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.generic.end.rpl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>math</key>
		<dict>
			<key>name</key>
			<string>meta.math.block.rpl</string>
			<key>begin</key>
			<string>\s*(--|[–—―])?\+</string>
			<key>end</key>
			<string>$|(?=#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#math-body</string>
				</dict>
			</array>
		</dict>
		<key>multiline-string</key>
		<dict>
			<key>name</key>
			<string>meta.multiline.group.rpl</string>
			<key>begin</key>
			<string>(?=@?`)</string>
			<key>end</key>
			<string>(?=^\s*[^\s`]|[^\s`#])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.triple.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>range</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.rpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.rpl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\d+|\$[\da-fA-F])(\+-|[+*~\-±])(\d+|\$[\da-fA-F])</string>
		</dict>
		<key>number</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.rpl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$[\da-fA-F]+|\d+)(?=\s*([:#,\]})]|$))</string>
		</dict>
		<key>reference</key>
		<dict>
			<key>begin</key>
			<string>(@)([\(\[]?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.mapping.begin.rpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.brace.reference.rpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[\)\]]|(?=\s*[^.])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.reference.rpl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#index</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(this|g*parent|w*back|Defs)|([^\s.{}()\[\]:#]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*[^.])</string>
				</dict>
			</array>
		</dict>
		<key>refstr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@)(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(“)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([“”])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(”)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([”„])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(„)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([“”])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(‟)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‟”])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(‘)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‘’])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(’)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‘’‚])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(‚)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‘’])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(‛)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‛’])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(『)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(』)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(」)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(』)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(«)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(»)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(»)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([«»])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(‹)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(›)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(›)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(‹)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)(--|[–—―])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.mapping.begin.rpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>string.interpolated.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(“)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([“”])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(”)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([”„])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(„)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([“”])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(‟)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‟”])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(‘)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‘’])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(’)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‘’‚])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(‚)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‘’])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(‛)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([‛’])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(『)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(』)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(「)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(」)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(«)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(»)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(»)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>([«»])|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(‹)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(›)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(›)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(‹)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.rpl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(--|[–—―])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.rpl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>string.quoted.other.rpl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>begin</key>
			<string>(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\[\](){}:#,][^\[\](){}:#,]</string>
					<key>name</key>
					<string>entity.name.type.rpl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-body</string>
				</dict>
			</array>
		</dict>
		<key>struct-body</key>
		<dict>
			<key>name</key>
			<string>meta.structbody</string>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(?![#\s])(?=(\w+\d*|\$[\da-fA-F]+|\d+|"($.|[^"]+)*"|“($.|[^“”]+)*[“”]|”($.|[^”„]+)*[”„]|„($.|[^“”]+)*[“”]|‟($.|[^‟”]+)*[‟”]|'($.|[^']+)*'|‘($.|[^‘’]+)*[‘’]|’($.|[^‘’‚]+)*[‘’‚]|‚($.|[^‘’]+)*[‘’]|‛($.|[^‛’]+)*[‛’]|『($.|[^』]+)*』|「($.|[^」]+)*」|«($.|[^»]+)*»|»($.|[^«»]+)*[«»]|‹($.|[^›]+)*›|›($.|[^‹]+)*‹)\s*:)</string>
					<key>comment</key>
					<string>this forcibly requires the colon to be on the same line as the keyname</string>
					<key>end</key>
					<string>(,)|$|^|(?=})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.object.comma.rpl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+\d*</string>
							<key>name</key>
							<string>support.variable.rpl</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.keyvalue</string>
							<key>begin</key>
							<string>:</string>
							<key>end</key>
							<string>(?=,|$|^|})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>(math)\s*(\()</string>
									<key>end</key>
									<string>\)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>storage.type.rpl</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>meta.brace.round.rpl</string>
										</dict>
									</dict>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>meta.brace.round.rpl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>storage.type.rpl</string>
									<key>patterns</key>
									<array>
										<!-- TODO: Highlight in string -->
										<dict>
											<key>include</key>
											<string>#string</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#math-body</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#value-struct</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct</string>
				</dict>
			</array>
		</dict>
		<key>value-struct</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\w+\d*(?=\s*[({\[])</string>
					<key>end</key>
					<string>(?&lt;=[)}\]])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.rpl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.brace.round.rpl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.brace.round.rpl</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#value-struct</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#struct-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#refstr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#range</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multiline-string</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>::?</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;![:\s])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rpl</string>
	<key>uuid</key>
	<string>5a9f0db4-5ce6-40e9-940e-a0ed4fba0949</string>
</dict>
</plist>
